
SELECT DISTINCT DIRECTOR, COUNT(TITLE)
FROM MOVIE
GROUP BY(DIRECTOR);

SELECT DISTINCT MOVIE.DIRECTOR, COUNT(MOVIE_ID.DOMESTIC_SALES), COUNT(MOVIE_ID.INTERNATIONAL_SALES)
FROM MOVIE_ID
LEFT JOIN MOVIE
ON MOVIE.ID = MOVIE_ID.ID
GROUP BY (MOVIE.DIRECTOR);