CREATE TABLE Movie(
ID NUMBER,
CONSTRAINT MOVIE_ID PRIMARY KEY(ID),
Title NVARCHAR2(50) UNIQUE NOT NULL,
Director NVARCHAR2(50) UNIQUE NOT NULL,
Year NUMBER CHECK (YEAR >= 1900 AND YEAR <= 2018),
Lenght_mins NUMBER CHECK(Lenght_mins >= 10 AND Lenght_mins <= 200)
);