CREATE TABLE ColumCategories(
ID NUMBER,
CONSTRAINT ColumCategories_PK PRIMARY KEY(ID),
Title VARCHAR2(64),
Description CLOB,
Dates TIMESTAMP,
IP NVARCHAR2(20)
);

CREATE TABLE ColumSubcategories(
ID NUMBER,
CONSTRAINT ColumSubcategories_PK PRIMARY KEY(ID),
IDCategory NUMBER,
CONSTRAINT ColumCategories_FK FOREIGN KEY (IDCategory) REFERENCES ColumCategories(ID),
Title NVARCHAR2(45),
Description CLOB,
Dates TIMESTAMP,
IP NVARCHAR2(20)
);

CREATE TABLE Users(
ID NUMBER,
CONSTRAINT Users_PK PRIMARY KEY(ID),
Nickname NVARCHAR2(16),
Password NVARCHAR2(128),
Email NVARCHAR2(128),
Dates TIMESTAMP,
Carma NUMBER(9,2),
IP NVARCHAR2(20)
);


CREATE TABLE TorumPosts(
ID NUMBER,
CONSTRAINT TorumPosts_PK PRIMARY KEY(ID),
IDSubcategory NUMBER,
CONSTRAINT Subcategory_FK FOREIGN KEY (IDSubcategory) REFERENCES ColumSubcategories (ID),
IDUser NUMBER,
CONSTRAINT User_FK FOREIGN KEY (IDUser) REFERENCES Users(ID),
ParentPost NUMBER,
CONSTRAINT ParentPost_FK FOREIGN KEY (ParentPost) REFERENCES TorumPosts(ID),
Title NVARCHAR2(90),
Content CLOB,
IsPoll CHAR,
Dates TIMESTAMP,
IP NVARCHAR2(20)
);

CREATE TABLE TorumPollsOptions(
ID NUMBER,
CONSTRAINT TorumPollsOptions_PK PRIMARY KEY(ID),
IDPost NUMBER,
CONSTRAINT IDPosts_FK FOREIGN KEY (IDPost) REFERENCES TorumPosts(ID),
Title NVARCHAR2(64),
Dates TIMESTAMP
);

CREATE TABLE TorumPollsOptionsotes(
ID NUMBER,
CONSTRAINT TorumPollsOptionsotes_PK PRIMARY KEY(ID),
IDPollsOptions NUMBER,
CONSTRAINT IDPollsOptions_FK FOREIGN KEY (IDPollsOptions) REFERENCES TorumPollsOptions(ID),
IDUser NUMBER,
CONSTRAINT IDUser_FK FOREIGN KEY (IDUser) REFERENCES Users(ID),
Dates TIMESTAMP,
IP NVARCHAR2(20)
);