CREATE TABLE ROOM(
ID NUMBER PRIMARY KEY,
NUMBER_OF_GUESTS NUMBER,
PRICE NUMBER,
BREAKFAST_INCLUDED NUMBER,
DATE_AVAILABLE_FROM TIMESTAMP,
HOTEL_ID NUMBER,
CONSTRAINT HOTEL_FK FOREIGN KEY(HOTEL_ID) REFERENCES HOTEL(ID)
);