CREATE TABLE ORDERS(
ID NUMBER PRIMARY KEY,
USERS_ID NUMBER,
CONSTRAINT USER_FK FOREIGN KEY(USERS_ID) REFERENCES USERS(ID),
ROOM_ID NUMBER,
CONSTRAINT ROOM_FK FOREIGN KEY(ROOM_ID) REFERENCES ROOM(ID),
DATE_FROM TIMESTAMP,
DATE_TO TIMESTAMP,
MONEY_PAID NUMBER
);