CREATE TABLE HOTEL(
ID NUMBER PRIMARY KEY,
NAME NVARCHAR2(64),
COUNTRY NVARCHAR2(64),
CITY NVARCHAR2(64),
STREET NVARCHAR2(64)
);
ALTER TABLE HOTEL ADD ROOM_ID NUMBER CONSTRAINT ROOM_FOK REFERENCES ROOM(ID);