CREATE TABLE USERS(
ID NUMBER PRIMARY KEY,
USER_NAME NVARCHAR2(64),
PASSWORD NVARCHAR2(64),
COUNTRY NVARCHAR2(64),
USER_TYPE NVARCHAR2(64),
ORDERS_ID NUMBER,
CONSTRAINT ORDERS_FK FOREIGN KEY(ORDERS_ID) REFERENCES ORDERS(ID)
LOGIN_STATUS NUMBER
);