SELECT CUSTOMER.CUSTNAME, CUSTOMER.CITY, SALESMAN.NAME, SALESMAN.CITY
FROM CUSTOMER
JOIN SALESMAN ON SALESMAN.Sulesman_id = CUSTOMER.Customer_id
JOIN DEAL ON DEAL.CUSTOMER_ID = CUSTOMER.Customer_id
WHERE DEAL.AMOUNT > 10000;

SELECT Custname
FROM customer
JOIN DEAL ON DEAL.CUSTOMER_ID = customer.Customer_id
WHERE EXTRACT(YEAR FROM DEAL.DATES) = 2018 AND EXTRACT(YEAR FROM DEAL.DATES) = 2017;

SELECT SALESMAN.NAME FROM SALESMAN
JOIN CUSTOMER ON SALESMAN.Sulesman_id = CUSTOMER.Customer_id
JOIN DEAL ON DEAL.CUSTOMER_ID = CUSTOMER.Customer_id
WHERE DEAL.AMOUNT = (SELECT MAX(DEAL.AMOUNT) FROM DEAL);

CREATE TABLE DEAL(
CUSTOMER_ID NUMBER,
CONSTRAINT CUST_FK FOREIGN KEY (CUSTOMER_ID) REFERENCES customer (Customer_id),
AMOUNT NUMBER NOT NULL,
DATES TIMESTAMP NOT NULL
);